name: Daily Auto Commit (Multiple)

on:
  schedule:
    - cron: '0 6 * * *' # Roz Indian time ke hisaab se dopahar 11:30 baje chalega
  workflow_dispatch: # Button se manually chalane ke liye

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: 6 Commits lagataar banao
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          
          # Yahan direct numbers likh diye hain taaki koi error na aaye
          for i in 1 2 3 4 5 6
          do
            echo "Commit number $i at $(date)" >> auto_update.txt
            git add auto_update.txt
            git commit -m "Daily contribution $i"
          done
          
          git push
